### PR TITLE
Add forum to menu

### PR DESCRIPTION
**Pull request by mluessi**
I think it's time to add a link to the forum. I know there were some concerns of not having enough posts for making it "official"  but it really is a chicken-egg problem; if no one knows the forum exists, we will never have people posting ;).

### CODE REVIEW

**Comment by VArcht** [comment]
All in favor say aye, VArcht says "Aye", all opposed?

**Comment by VArcht** [comment]
hah, was just going to do that @mlyle

**Comment by mlyle** [comment]
:D lol

**Comment by mlyle** [comment]
Edited wiki, posted message to google group, linked from channel topic

**Pull request merged**
