### PR TITLE
attempt to enable continuous integration

### PR DESCRIPTION
**Pull request by mlyle**
(wip)

### CODE REVIEW

**Comment by tracernz** [comment]
I was looking at this last night too. :+1:

**Comment by tracernz** [comment]
One thing I think would be cool... is to post stderr as a Github comment if the build fails. Should be possible with the Github API and a Travis secret env. var. Good place to test it before doing it on the main repo (where it is much more useful since port 8080 isn't accessible for everyone).

**Comment by mlyle** [comment]
Is travis on 8080?  Should be able to just view it from the 'show all checks'.

I **would** like to be able to post the built site somewhere, but that's rather tricky all in all (where-- s3, github, etc..., and how)... could commit it to a github repo, but then how does it age out/how do we avoid spam/malware/etc.

**Comment by tracernz** [comment]
Could put it in an S3 bucket and set the policy for the bucket to delete old stuff (can use one of mine. this was the plan I came up with last night).

By main repo I mean "d-ronin/dRonin", where Jenkins CI is on 8080 so I can't see it at work. :wink:

**Comment by tracernz** [comment]
https://aws.amazon.com/blogs/aws/amazon-s3-object-expiration/

**Comment by tracernz** [comment]
Ready for merge? I can do S3 on top.

**Comment by tracernz** [comment]
Ah, FFS, it can't work for PR builds: https://github.com/travis-ci/travis-ci/issues/5579

**Comment by mlyle** [comment]
Ah, I understand better.  Yes, stderr would be neat on main repo.

Yes, this is ready for merge.

**Comment by mlyle** [comment]
(Though this changes fundamental stuff, so after merge I think the site should get peeked at quickly and we be ready to revert)

**Comment by mlyle** [comment]
Can this merge too please (so CI will work on other PRs)

**Pull request merged**
