### PR TITLE
Windows Dev Environment Setup doc changes

### PR DESCRIPTION
**Pull request by ewingate**
I've put a direct link to the ISO file hosed by MS for MSVC2015, original link is to a page that hides it well enough that I gave up.  Added new image for Qt setup and updated the MinGW version needed as well as Qt Charts (needed for GCS build).

### CODE REVIEW

**Comment by tracernz** [comment]
Thanks! The CI fails appear unrelated to your changes.

```
- ./_site/docs/advanced-configurations/programming-escs-with-passthrough/index.html
  *  External link https://www.mediafire.com/folder/dx6kfaasyo24l/BLHeliSuite failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: SSL connect error
- ./_site/docs/index.html
  *  External link https://mademistakes.com/work/minimal-mistakes-jekyll-theme failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: SSL connect error
htmlproofer 3.7.3 | Error:  HTML-Proofer found 2 failures!
```
https://mademistakes.com/work/minimal-mistakes-jekyll-theme works for me, can't check the mediafire link atm.

**Comment by mlyle** [comment]
Yah, the links work.  It's some jekyll-is-running-dumb-package-versions problem, i'm trying to fix it.

**Comment by ewingate** [comment]
Neither of those links have anything to do with my edits.

**Comment by mlyle** [comment]
Right, I know ;)

**Comment by mlyle** [comment]
Looks good and is up live.  Thanks :D

**Pull request merged**
