### PR TITLE
Home changes

### PR DESCRIPTION
**Pull request by chasd00**
Started with a few changes but turned into a lot. The biggest change is moving the autotune stats table to the main page. Re-worked the nav too, all the content and information is preserved but, at the end of the day, the user is either going to hit the wiki or go straight to releases.

### CODE REVIEW

**Comment by chasd00** [comment]
Here's a couple screenshots
dronin-screenshot
dronin-screenshot-popup

**Comment by VArcht** [comment]
The housekeeping stuff is great. 

I don't like the idea of the tunes being on the home page. I like the idea of live/fresh content on the home page but this is not it.

Got to run I'll give things a closer look later.

**Comment by chasd00** [comment]
no sweat, just let me know

**Comment by tracernz** [comment]
Ohhh, the autotune looks really nice. Maybe put it on it's own page?

**Comment by VArcht** [comment]
I agree the at results look really nice. I would like to keep most of the info(marketing) we have currently. Current layout could be cleaned up (a lot).

**Comment by chasd00** [comment]
If Autotune is on its own page then would the user get to it from a link on the wiki? That would make sense to me since there's a learning curve to understanding Autotown and the meaning behind the numbers being presented. Plus, I've found there's a *lot* of good data in the Autotown system. Educating the user on how to use the Autotown data to their advantage could be a handful of wiki pages on its own.

By the way, what's the best way to handle pull request? Should I close it then you guys just review my fork and when you like what you see I create a pull request?

**Comment by VArcht** [comment]
If you replaced the autotune page with yours I'd merge it yesterday.

**Comment by chasd00** [comment]
will replace this with a pull request for just the autotune page

**Pull request closed without merging**
